on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1